import "@/styles/globals.css";
import { Poppins } from "next/font/google";
import { cookies } from "next/headers";
import { TRPCReactProvider } from "@/trpc/react";
import AntdProvider from "@/components/AntdProvider";

const poppins = Poppins({
  subsets: ["latin"],
  variable: "--font-poppins",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata = {
  title: "Buku Tamu - T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
  manifest: "/manifest.json",
};

type Props = { children: React.ReactNode };

export default function RootLayout({ children }: Props) {
  return (
    <html lang="en">
      <body className={`font-poppins ${poppins.variable}`}>
        <TRPCReactProvider cookies={cookies().toString()}>
          <AntdProvider>
            <main>{children}</main>
          </AntdProvider>
        </TRPCReactProvider>
      </body>
    </html>
  );
}
